// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StudentServisWebScraper.Api.Data;
using System;

namespace StudentServisWebScraper.Api.Migrations
{
    [DbContext(typeof(StudentServisWebScraperDataContext))]
    [Migration("20180221110739_DateColumnRename")]
    partial class DateColumnRename
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentServisWebScraper.Api.Data.JobOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<int>("Code");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactPhone");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateLastSeen");

                    b.Property<DateTime?>("DateRemoved");

                    b.Property<decimal?>("HourlyPay");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("JobOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
